spring.application.name=connect-rural-api


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# WhatsApp Business Cloud API
whatsapp.webhook.verify-token=${WHATSAPP_VERIFY_TOKEN:change-me-in-env}
