spring.application.name=connect-rural-api


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# WhatsApp Gateway
whatsapp.gateway.url=${WHATSAPP_GATEWAY_URL:http://localhost:8081}
app.base-url=${APP_BASE_URL:http://localhost:8080}
